server:
  port: 8081
  servlet:
    encoding:
      force: true
    context-path: /jianmu_saas
spring:
  config:
    activate:
      on-profile: @profile.active@
  datasource:
    url: jdbc:h2:mem:db;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 60
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    out-of-order: false
    validate-on-migrate: true
    encoding: UTF-8
  jackson:
    parser:
      ALLOW_UNQUOTED_CONTROL_CHARS: true
    default-property-inclusion: non_null
  main:
    banner-mode: off

springdoc:
  packages-to-scan: dev.jianmu.api.controller

pagehelper:
  support-methods-arguments: true
logging:
  charset:
    console: UTF-8

mybatis:
  configuration:
    jdbc-type-for-null: null

jianmu:
  api:
    # jwt-secret 长度不小于256位
    jwt-secret: A1KLCSAFHCASLHVCAHVKJAHSVWGEEQKWBY3CJBTI9G20ZPXYFGAVEHQUTPWOURHOO5CKVOIE2RYMP4L9JRG3ZROSWLBXCSHBMCLGUHGHMOPZD7BLHQNLLH7JLVLHOJBGM5IQVYER2EKFXL9HPRKXVWZYHB9VUQ6VJEWC0UMDU67KWNP6TUG1TDPSG1OLYZ0OO4KWI0TB2SMQCPKIGWDJEM7VIIO4JLWY0SSV6C0SAVBP0WZXPYDUWGDYCI7XXHBWO3ITTBEKX7Z9YC6RNIATMWGOJLF3DCQSQAEHRERFE41DLLV9VSOQFFH2CCSKAIUY24LE3MGA2QMMY7MI0IDV
    jwt-expiration-ms: 86400000
    admin-passwd: 123456
  global:
    record:
      auto-clean: true
      max: 100
registry:
  version: @project.version@
  type: @project.build.finalName@
  url: https://jianmuhub.com
credential:
  type: local
storage:
  filepath: data
