server:
  port: 8081
  servlet:
    encoding:
      force: true
spring:
  config:
    activate:
      on-profile: @profile.active@
  datasource:
    url: jdbc:h2:mem:db;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password: sa
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    out-of-order: false
    validate-on-migrate: true
    encoding: UTF-8
  jackson:
    parser:
      ALLOW_UNQUOTED_CONTROL_CHARS: true
  main:
    banner-mode: off

springdoc:
  packages-to-scan: dev.jianmu.api.controller

pagehelper:
  support-methods-arguments: true
logging:
  charset:
    console: UTF-8

mybatis:
  configuration:
    jdbc-type-for-null: null

embedded:
  docker-worker:
    docker-host: tcp://127.0.0.1:2375
    api-version: v1.39
jianmu:
  api:
    jwtSecret: Hahhahhhaahh
    jwtExpirationMs: 86400000
    adminPasswd: 123456
  global:
    record:
      auto-clean: true
      max: 100
registry:
  version: @project.version@
  type: @project.build.finalName@
  url: https://hub.jianmu.dev
credential:
  type: local
